{
 "title": "Tomcat",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"tomcat_jvm_memory\" WITH KEY = \"host\""
   },
   {
    "name": "NameMemoryPool",
    "query": "SHOW TAG VALUES FROM \"tomcat_jvm_memorypool\" WITH KEY = \"name\""
   },
   {
    "name": "NameConnector",
    "query": "SHOW TAG VALUES FROM \"tomcat_connector\" WITH KEY = \"name\""
   },
   {
    "name": "TypeMemoryPool",
    "query": "SHOW TAG VALUES FROM \"tomcat_jvm_memorypool\" WITH KEY = \"type\""
   }
  ]
 },
 "panels": [
  {
   "title": "Tomcat JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memory",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memory",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memory",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Tomcat JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memorypool",
     "query": "SELECT mean(\"committed\") FROM \"tomcat_jvm_memorypool\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameMemoryPool$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$TypeMemoryPool$/" }
     ]
    },
    {
     "alias": "Init",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memorypool",
     "select": [
      [
       { "params": [ "init" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameMemoryPool$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$TypeMemoryPool$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memorypool",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameMemoryPool$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$TypeMemoryPool$/" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memorypool",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameMemoryPool$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$TypeMemoryPool$/" }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Connector Bytes Sent/Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Connector Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "max_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    },
    {
     "alias": "Current Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "current_thread_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    },
    {
     "alias": "Busy Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "current_threads_busy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Connector Requests/Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "request_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    },
    {
     "alias": "Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "error_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Connector Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Processing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "processing_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "max_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NameConnector$/" }
     ]
    }
   ]
  }
 ]
}