{
 "title": "WildFly",
 "tags": [ "JavaApplicationServer" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"jboss.jvm_memory\" WITH KEY = \"host\""
   },
   {
    "name": "Datasource",
    "query": "SHOW TAG VALUES FROM \"jboss.datasource.pool\" WITH KEY = \"data-source\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "GC",
    "label": "Garbage Collector",
    "query": "SHOW TAG VALUES FROM \"jboss.jvm_garbage_collector\" WITH KEY = \"name\""
   },
   {
    "name": "MemoryPool",
    "query": "SHOW TAG VALUES FROM \"jboss.jvm_memory_pool\" WITH KEY = \"pool_name\" WHERE \"host\" =~ /^$Host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request/Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Requests",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.connectors.http",
       "select": [
        [
         { "params": [ "requestCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Errors",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.connectors.http",
       "select": [
        [
         { "params": [ "errorCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Sent/Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Received",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.connectors.http",
       "select": [
        [
         { "params": [ "bytesReceived" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Sent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.connectors.http",
       "select": [
        [
         { "params": [ "bytesSent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Init",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Init",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gabage Collection ($GC)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "GC",
   "collapsed": true,
   "panels": [
    {
     "title": "Collection Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Collections",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_garbage_collector",
       "select": [
        [
         { "params": [ "CollectionCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GC$/" }
       ]
      }
     ]
    },
    {
     "title": "Collection Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_garbage_collector",
       "select": [
        [
         { "params": [ "CollectionTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GC$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Datasources ($Datasource)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Datasources",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Active",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.datasource.pool",
       "select": [
        [
         { "params": [ "ActiveCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "data-source", "operator": "=~", "value": "/^$Datasource$/" }
       ]
      },
      {
       "alias": "Available",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.datasource.pool",
       "select": [
        [
         { "params": [ "AvailableCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "data-source", "operator": "=~", "value": "/^$Datasource$/" }
       ]
      }
     ]
    },
    {
     "title": "Prepared Statement Cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.datasource.jdbc",
       "select": [
        [
         {
          "params": [
           "PreparedStatementCacheAccessCount"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "data-source", "operator": "=~", "value": "/^$Datasource$/" }
       ]
      },
      {
       "alias": "Hit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.datasource.jdbc",
       "select": [
        [
         { "params": [ "PreparedStatementCacheHitCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "data-source", "operator": "=~", "value": "/^$Datasource$/" }
       ]
      },
      {
       "alias": "Miss",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.datasource.jdbc",
       "select": [
        [
         {
          "params": [
           "PreparedStatementCacheMissCount"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "data-source", "operator": "=~", "value": "/^$Datasource$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "System CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "CPU Load",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_operating_system",
       "select": [
        [
         { "params": [ "SystemCpuLoad" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Process CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "CPU Load",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_operating_system",
       "select": [
        [
         { "params": [ "ProcessCpuLoad" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Pool ($MemoryPool)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "MemoryPool",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Init",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Pool ($MemoryPool)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Init",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Pool ($MemoryPool)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      },
      {
       "alias": "Init",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jboss.jvm_memory_pool",
       "select": [
        [
         { "params": [ "Usage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "pool_name", "operator": "=~", "value": "/^$MemoryPool$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}