{
 "title": "MongoDB",
 "tags": [ "Database" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"mongodb\" WITH KEY = \"host\""
   },
   {
    "name": "DB",
    "query": "SHOW TAG VALUES FROM \"mongodb_db_stats\" WITH KEY = \"db_name\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "Collection",
    "query": "SHOW TAG VALUES FROM \"mongodb_col_stats\" WITH KEY = \"collection\" WHERE \"db_name\" =~ /^$DB$/"
   }
  ]
 },
 "panels": [
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Queries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "queries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Inserts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "inserts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Deletes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "deletes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Updates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "updates" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Database ($DB)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "DB" },
  {
   "title": "Collections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "collections" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "objects" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "data_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" }
     ]
    },
    {
     "alias": "Index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "index_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" }
     ]
    },
    {
     "alias": "Storage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "storage_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "indexes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Object Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "avg_obj_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  { "title": "Collections ($Collection)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "Collection" },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_col_stats",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" },
      { "condition": "AND", "key": "collection", "operator": "=~", "value": "/^$Collection$/" }
     ]
    },
    {
     "alias": "Storage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_col_stats",
     "select": [
      [
       { "params": [ "storage_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" },
      { "condition": "AND", "key": "collection", "operator": "=~", "value": "/^$Collection$/" }
     ]
    },
    {
     "alias": "Index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_col_stats",
     "select": [
      [
       { "params": [ "total_index_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" },
      { "condition": "AND", "key": "collection", "operator": "=~", "value": "/^$Collection$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Object Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_col_stats",
     "select": [
      [
       { "params": [ "avg_obj_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" },
      { "condition": "AND", "key": "collection", "operator": "=~", "value": "/^$Collection$/" }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Objects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_col_stats",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$DB$/" },
      { "condition": "AND", "key": "collection", "operator": "=~", "value": "/^$Collection$/" }
     ]
    }
   ]
  }
 ]
}