{
 "title": "SQL Server",
 "tags": [ "Database" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"sqlserver_server_properties\" WITH KEY = \"host\""
   },
   {
    "name": "DB",
    "query": "SHOW TAG VALUES FROM \"sqlserver_database_io\" WITH KEY = \"database_name\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "Command",
    "query": "SHOW TAG VALUES FROM \"sqlserver_requests\" WITH KEY = \"command\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "MemoryClerk",
    "query": "SHOW TAG VALUES FROM \"sqlserver_memory_clerks\" WITH KEY = \"clerk_type\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "WaitCategory",
    "query": "SHOW TAG VALUES FROM \"sqlserver_waitstats\" WITH KEY = \"wait_category\""
   },
   { "name": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Process CPU",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_cpu",
       "select": [
        [
         { "params": [ "sqlserver_process_cpu" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "RAM",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_server_properties",
       "select": [
        [
         { "params": [ "server_memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Requests ($Command)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "Command",
   "collapsed": true,
   "panels": [
    {
     "title": "Request Time - $Command",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Total Time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_requests",
       "select": [
        [
         { "params": [ "total_elapsed_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "command", "operator": "=~", "value": "/^$Command$/" }
       ]
      },
      {
       "alias": "Wait Time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_requests",
       "select": [
        [
         { "params": [ "wait_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "command", "operator": "=~", "value": "/^$Command$/" }
       ]
      }
     ]
    },
    {
     "title": "Reads/Writes - $Command",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Reads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_requests",
       "select": [
        [
         { "params": [ "logical_reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "Edward-ASPIREV" },
        { "condition": "AND", "key": "command", "operator": "=~", "value": "/^$Command$/" }
       ]
      },
      {
       "alias": "Writes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_requests",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "command", "operator": "=~", "value": "/^$Command$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Database I/O ($DB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "DB",
   "collapsed": true,
   "panels": [
    {
     "title": "Reads/Writes - $DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Reads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_database_io",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DB$/" }
       ]
      },
      {
       "alias": "Writes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_database_io",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DB$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Read/Write - $DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "alias": "Read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_database_io",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DB$/" }
       ]
      },
      {
       "alias": "Write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_database_io",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DB$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency - $DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_database_io",
       "select": [
        [
         { "params": [ "read_latency_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DB$/" }
       ]
      },
      {
       "alias": "Write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_database_io",
       "select": [
        [
         { "params": [ "write_latency_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DB$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Waits ($WaitCategory)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "WaitCategory",
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Time - $WaitCategory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Wait Time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_waitstats",
       "select": [
        [
         { "params": [ "wait_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "wait_category", "operator": "=~", "value": "/^$WaitCategory$/" }
       ]
      },
      {
       "alias": "Resource Wait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_waitstats",
       "select": [
        [
         { "params": [ "resource_wait_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "wait_category", "operator": "=~", "value": "/^$WaitCategory$/" }
       ]
      },
      {
       "alias": "Signal Wait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_waitstats",
       "select": [
        [
         { "params": [ "signal_wait_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "wait_category", "operator": "=~", "value": "/^$WaitCategory$/" }
       ]
      }
     ]
    },
    {
     "title": "Waiting Tasks - $WaitCategory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Tasks",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_waitstats",
       "select": [
        [
         { "params": [ "waiting_tasks_count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "wait_category", "operator": "=~", "value": "/^$WaitCategory$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerk ($MemoryClerk)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "MemoryClerk",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Clerks - $MemoryClerk",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "Size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_memory_clerks",
       "select": [
        [
         { "params": [ "size_kb" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "clerk_type", "operator": "=~", "value": "/^$MemoryClerk$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}